@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.token}}

# @name register_user
Post {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Mário César",
  "username": "mariocesar",
  "email": "mario@gmail.com",
  "password": "123456",
  "phone": "568 12 38",
  "address": "Achada G. Trás",
  "role": "ADMIN",
  "stato": "true",
  "avatarURL": "https://github.com/mariocesar33.png"
}

###

# @name authenticate
Post {{baseUrl}}/sessions
Content-Type: application/json

{
  "username": "mariocesar",
  "password": "123456"
}

###

# @name refresh_token
Patch {{baseUrl}}/token/refresh
Content-Type: application/json

{
  "username": "mariocesar",
  "password": "123456"
}

###

# @name get_user_profile
GET {{baseUrl}}/me
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create_user_1
Post {{baseUrl}}/create-user
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Mayk Brito",
  "username": "maykbrito",
  "email": "mayke@gmail.com",
  "password": "123456",
  "phone": "21 994132-7777",
  "address": "Rio Grande do Sul",
  "role": "CLIENT",
  "stato": "true",
  "avatarURL": "https://github.com/maykbrito.png"
}

###

# @name create_user_2
Post {{baseUrl}}/create-user
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Diego Fernandes",
  "username": "diego",
  "email": "diego@gmail.com",
  "password": "123456",
  "phone": "21 994132-8888",
  "address": "Rio Grande do Sul",
  "role": "CLIENT",
  "stato": "true",
  "avatarURL": "https://github.com/diego3g.png"
}

###

# @name create_user_3
Post {{baseUrl}}/create-user
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Rodrigo Gonçalves",
  "username": "rodrigo",
  "email": "rodrigo@gmail.com",
  "password": "123456",
  "phone": "21 994132-9999",
  "address": "Rio Grande do Sul",
  "role": "CLIENT",
  "stato": "true",
  "avatarURL": "https://github.com/orodrigogo.png"
}